# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1axgKEhdYBznA6rYeCF2s_IpC1B0IGH-Y
"""

# 1 - Crie um programa para efetuar a leitura de um número inteiro e apresentar o resultado do quadrado deste número.

num = int(input('Digite um número: '))
nuns = (num * num)
print('O qaudrado desse número é: ' , nuns)

print("")
print("=========================================================================================================")
print("")

# 2 - Crie duas variáveis para armazenar seu primeiro nome e sobrenome.
# Em seguida, concatene-as para formar seu nome completo e exiba o resultado.

prim_nome = input('Digite seu primeiro nome: ')
seg_nome = input('Digite seu segundo nome: ')
print('Seu nome é' , prim_nome , seg_nome)

print("")
print("=========================================================================================================")
print("")

# 3 - Peça ao usuário para digitar dois números inteiros e armazene-os em variáveis.
# Realize a concatenação desses números como strings e exiba o resultado.

nun = input('Digite um número: ')
nun1 = input('Digite outro número: ')
print('A junção desses dois numeros formam' , nun + nun1)

print("")
print("=========================================================================================================")
print("")

# 4 - Crie uma variável para armazenar a palavra "Python".
# Em seguida, adicione um número inteiro ao final da palavra usando a concatenação e exiba o resultado.

py = ('Python')
n = 1000
print(py , 'é nota' , n)

print("")
print("=========================================================================================================")
print("")

# 5 - Declare uma variável contendo uma frase.
# Em seguida, peça ao usuário para digitar uma palavra e concatene essa palavra no final da frase. Exiba o resultado.

frase = ('A minha vida é muito')
palavra = input('Digite uma palavra: ')
print(frase , palavra)

print("")
print("=========================================================================================================")
print("")

# 6 - Crie três variáveis para armazenar a quantidade de horas, minutos e segundos.
# Concatene esses valores para formar uma mensagem de tempo no formato "hh:mm:ss".

pergunta = ('As que horas vc saio de casa?')
horas = input('Horas: ')
minutos = input('Minutos: ')
segundos = input('Segundos: ')
resposta = ('Eu sai de casa ás')
print(pergunta)
print(resposta , horas + ':' + minutos + ':' + segundos)

print("")
print("=========================================================================================================")
print("")

# 7 - Declare duas variáveis com números de telefone, incluindo um código de área e o número principal.
# Concatene esses valores para formar um número de telefone completo.

Numarea = input('Número de área: ')
NumDDD = input('Digite sue número de DDD: ')
NumCel = input('Digite seu número de celular: ')
print('Seu número de área, DDD e celular é:' , Numarea ,'(' +NumDDD+ ')' , NumCel)

print("")
print("=========================================================================================================")
print("")

# 8 - Crie uma lista de ingredientes para uma receita.
# Use concatenação para formar uma única string que liste os ingredientes separados por vírgulas.

ingrediente1 = input('Primeiro ingrediente: ')
ingrediente2 = input('Sugundo ingrediente: ')
ingrediente3 = input('terceiro ingrediente: ')
print('Eu preciso de ' + ingrediente1 + ', ' + ingrediente2 + ' e ' + ingrediente3 + '.')

print("")
print("=========================================================================================================")
print("")

# 9 - Peça ao usuário para digitar três adjetivos e armazene-os em variáveis.
# Em seguida, use essas palavras para criar uma frase concatenada que descreve algo interessante.

Adjt = input("Digite um adjetivo: ")
Adjt2 = input("Digite outro adjetivo: ")
Adjt3 = input("digite mais um adjetivo: ")

print('O mundo é muito' , Adjt + ',' , Adjt2 , 'e' , Adjt3 , '.')

## Aula 7

# **Exercício 1: Contagem regressiva simples**
# Escreva um programa que exiba uma contagem regressiva de 10 a 1, e depois imprima "Fogo!".

contagem = 10

while contagem >= 1:
      print(contagem)
      contagem -= 1
      if contagem == 0:
         print('Fogo!!')


# **Exercício 2: Soma de números pares**
# Peça ao usuário que insira um número inteiro positivo e, em seguida, calcule a soma de todos os números pares de 2 até o número inserido.

numeros = int(input("Digite um número inteiro positivo: "))
soma = 0
i = 2

while i <= numeros:
      soma += i
      i += 2

print("A soma dos números pares é:", soma)


# **Exercício 3: Tabuada de multiplicação**
# Peça ao usuário para inserir um número inteiro e mostre a tabuada de multiplicação desse número de 1 a 10.

numero = int(input("Digite um número inteiro: "))
i = 1

while i <= 10:
        resultado = numero * i
        print(f"{numero} x {i} = {resultado}")
        i += 1

# **Exercício 4: Números ímpares reversos**
# Exiba uma contagem regressiva de números ímpares de 99 a 1.

nun_imp = 99

while nun_imp >= 1:
      print(nun_imp)
      nun_imp -= 2

## Aula 8

# 1 -  Crie uma tupla chamada `frutas` com pelo menos 5 frutas diferentes. Em seguida, acesse e imprima o terceiro elemento da tupla.

tupla_frutas = ('melancia','mamão','abacaxi','pera','caju')
fruta = tupla_frutas[3]
print(fruta)

# 2 - Crie uma tupla chamada `numeros` com alguns números inteiros. Em seguida, converta essa tupla em uma lista e imprima a lista resultante.

tupla_numeros = (1,2,5,6,3,8,6)
nuns = list(tupla_numeros)
print(nuns)

# 3 - Crie uma tupla chamada `meses` com os nomes dos meses do ano até Setembro. Use um loop `for` para imprimir cada mês em uma linha separada.

tupla_meses = ('Janeiro','Fevereiro','Março','Abril','Maio','Junho','Junho','Agosto','Setembro')
meses = list(tupla_meses)
for m in meses:
    print(m)

# 4 - Crie uma lista chamada `notas` com algumas notas de alunos. Em seguida, converta essa lista em uma tupla e imprima a tupla resultante.

lista_notas = [10,7,5,8,9,8,3,4]
nota = tuple(lista_notas)
print(nota)

# 5 - Crie uma lista chamada `ponto` que represente as coordenadas (x, y) de um ponto. Em seguida, desempacote os elementos da lista em duas variáveis separadas (x e y) e imprima os valores.

lista_ponto = [10,20]
x,y = lista_ponto
print('Ponto X:', x)
print('Ponto Y:', y)